site_name: origami
pages:
  - Home: index.md
  - Foreach school: foreach.md
  - Combinators: combinators.md
  - Standard Folds: standard.md
  - Breakable Folds: breakable.md
  - Iterator: iterator.md
  - Input stream: inputstream.md
  - Sinks: sinks.md
  - Process: process.md
  - SafeT: safet.md
  - Type aliases: typealiases.md
  - Implicits: implicits.md
theme: readthedocs
